### ISSUE TITLE
Corrigir pequenos bugs

### ISSUE THREAD

**Issue by biaduque** [raphaelalkamim/macroChallengeEvents#179]
### To-Do

- [x]  Criar lógica que sobe json no app automaticamente
- [x]  Refatorar consulta da API para chamar só 1x
- [x]  Destacar mais o wimbi e deixar ele primeiro
- [x]  Rever categorias (localização) @Carolina Ortega
- [x]  Corrigir foto de empty da current @Carolina Ortega
- [x]  Corrigir a foto empty do explorar @Beatriz Duque
- [x]  Adicionar nome do usuário na visualização da viagem @Beatriz Duque
- [x]  Corrigir scroll da collection de info (diminuir o delay)@Beatriz Duque
- [x]  Rever tamanho dos widgets @Beatriz Duque
- [x]  Dar PR nas correções @Carolina Ortega
    - [x]  mudar o tom do vermelho do deletar e sair da conta no darkmode @Carolina Ortega @Juliana Santana
    - [x]  empty state sem atividade no explorar @Carolina Ortega
