### ISSUE TITLE
💻 Corrigindo bugs

### ISSUE THREAD

**Issue by cahhortega** [raphaelalkamim/macroChallengeEvents#99]

**Comment by biaduque** [comment]
- [ ] Corrigir imagem esticada quando adicionada 
- [ ] Corrigir empty do contato e link (modal de detalhe da atividade) na navegação do Profile

**Comment by biaduque** [comment]
[Página do Notion com to-do](https://www.notion.so/academy2021/Daily-8a14bffb9088438785cae02e1a83f265)

### To-Do
- [x]  valores mockados no modal de atividades
- [x]  Dupliquei e foi adicionado no “explorar” @Beatriz Duque
- [x]  ordenar por mais curtidas no explorar @Beatriz Duque
- [x]  ajustar custo do explore @Beatriz Duque
    - [x]  ajustar a matemática do dinheiro na tela inicial
- [x]  ter um loading entre o explorar e o roteiro, ao invés de aparecer o mokado por segundos @Beatriz Duque
- [x]  valor total de Toronto 3 pessoas tá zuado @Beatriz Duque
- [x]  código crasha quando abre um link que não existe @Beatriz Duque
- [x]  quando clicar na foto em "editar perfil” abrir o alerta de mudar foto @Beatriz Duque
- [x]  primeiro dia da viagem no explorar nao mostra as atividades @Beatriz Duque
- [x]  teclado de nova atividade não desce quando você clica na tela @Beatriz Duque
- [x]  scroll de dias cortado @Carolina Ortega
- [x]  trocar a ordem de sair com deletar conta @Carolina Ortega
- [ ]  mudar o tom do vermelho do deletar e sair da conta no darkmode @Carolina Ortega @Juliana Santana
- [x]  tirar o ícone de filtro na página de explorar @Carolina Ortega
- [x]  notificação não tá salvando @Carolina Ortega @Luca H. @Beatriz Duque
- [x]  empty state sem atividade no explorar @Carolina Ortega
- [ ]  Localização @Carolina Ortega
    - [x]  localizar o alerta de sair da conta
    - [ ]  localizar onboarding
    - [x]  contact - tradução, na página de criar atividade
    - [x]  localizar login
- [x]  corrigir ordem dos botões de alerta de juntar-se @Carolina Ortega
- [x]  a tela de login precisa do textin @Carolina Ortega
- [x]  adicionar termos @Carolina Ortega
- [x]  talvez fazer de ao clicar na bolinha de perfil, redirecionar para editar perfil @Carolina Ortega
- [x]  constraints do botao de rota @Carolina Ortega
- [x]  constraints do switch button criar viagem @Carolina Ortega
- [x]  arrumar foto do roteiro @Carolina Ortega @Beatriz Duque
- [x]  subir json com roteiros para quando o backend estiver vazio
